layout_spectrum: 0.4500600740959001
typography_spectrum: 0.33620954365026906
color:
  brandStrength: 0.621574727015035
  lightness: 0.7272341376113346
  saturation: 0.5532626591798029
  rhythmicContrast: 0.28812931214274823
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: JuanFra Photography
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: article
    html: >-
      <article><h1>JuanFra Photography</h1><img
      src="https://juanfraphotography.files.wordpress.com/2017/03/cropped-jfphoto_logosymbol_hres.png?w=200"></article>
    src: >-
      https://juanfraphotography.files.wordpress.com/2017/03/cropped-jfphoto_logosymbol_hres.png?w=200
    metadata:
      author:
        - name: JuanFra Photography
          url: 'https://juanfraphotography.wordpress.com/author/juanfraphotography/'
          avatar: {}
      related: []
      publisher:
        url: 'https://juanfraphotography.wordpress.com'
        name: JuanFra Photography
        favicon: >-
          https://juanfraphotography.files.wordpress.com/2017/03/cropped-jfphoto_logosymbol_hres.png?w=192
        domain: juanfraphotography.wordpress.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      isBasedOnUrl: 'https://juanfraphotography.wordpress.com'
      title: JuanFra Photography
      datePublished: null
    title: JuanFra Photography
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
url: 'https://juanfraphotography.com'
purpose: []
github: true
author:
  name: Copyright 2017 JuanFra Photography - Powered by Mobywise
  email: info@mobywise.com
  url: 'https://www.mobywise.com'
title: ''
description: ''
