typography_spectrum: 0.14891071570677555
color:
  brandStrength: 0.6436497512707801
  lightness: 0.4355011065589209
  saturation: 0.624471151098277
  rhythmicContrast: 0.2339459632013436
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
github: true
layout_spectrum: 0.5905562938380949
author:
  name: Copyright 2017 JuanFra Photography - Powered by Mobywise
  email: info@mobywise.com
  url: 'https://www.mobywise.com'
name: ' '
url: 'https://juanfraphotography.com'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Portafolio
    id: 272fbd21-6779-417c-a41f-5db41bb2774f
    type: content
  - name: Blog
    id: 314f3c4a-d6db-44ef-a1bf-6f7ea9176ad2
    type: content
title: ''
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="http://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FGxsxM7PHvUc%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DGxsxM7PHvUc&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FGxsxM7PHvUc%2Fhqdefault.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      datePublished: null
      isBasedOnUrl: 'http://youtu.be/GxsxM7PHvUc'
      keywords:
        - video
        - sharing
        - camera phone
        - video phone
        - free
        - upload
      related: []
      author:
        - name: Mobywise Watch
          url: 'https://www.youtube.com/channel/UCxqFu6qTdYmE8IEkKJIdHBw'
          avatar: {}
      '@context': 'http://schema.org'
      title: JFPhoto Reel 1
      '@type': VideoObject
      app_links: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: youtu.be
      description: JuanFra Photography
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: ''
purpose: []
