layout_spectrum: 0.05911502434761439
typography_spectrum: 0.5619135670505907
color:
  brandStrength: 0.7718969812398168
  lightness: 0.5598282844865566
  saturation: 0.5328431387087976
  rhythmicContrast: 0.572253145316044
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: JuanFra Photography
content: []
url: 'https://juanfraphotography.com'
purpose: []
github: true
author:
  name: Copyright 2017 JuanFra Photography - Powered by Mobywise
  email: info@mobywise.com
  url: 'https://www.mobywise.com'
