layout_spectrum: 0.4500600740959001
typography_spectrum: 0.33620954365026906
color:
  brandStrength: 0.621574727015035
  lightness: 0.7272341376113346
  saturation: 0.5532626591798029
  rhythmicContrast: 0.28812931214274823
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: JuanFra Photography
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="http://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FGxsxM7PHvUc%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DGxsxM7PHvUc&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FGxsxM7PHvUc%2Fhqdefault.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Mobywise Watch
          url: 'https://www.youtube.com/channel/UCxqFu6qTdYmE8IEkKJIdHBw'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: youtu.be
      keywords:
        - video
        - sharing
        - camera phone
        - video phone
        - free
        - upload
      description: JuanFra Photography
      '@type': VideoObject
      app_links: []
      '@context': 'http://schema.org'
      isBasedOnUrl: 'http://youtu.be/GxsxM7PHvUc'
      title: JFPhoto Reel 1
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
url: 'https://juanfraphotography.com'
purpose: []
github: true
author:
  name: Copyright 2017 JuanFra Photography - Powered by Mobywise
  email: info@mobywise.com
  url: 'https://www.mobywise.com'
title: ''
description: ''
